# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OpenSwmmOutFile <- function(outFile) {
    .Call('_swmmr_OpenSwmmOutFile', PACKAGE = 'swmmr', outFile)
}

GetSwmmResultPart_ <- function(iType, objIndices, varIndices, firstPeriod, lastPeriod) {
    .Call('_swmmr_GetSwmmResultPart_', PACKAGE = 'swmmr', iType, objIndices, varIndices, firstPeriod, lastPeriod)
}

GetSwmmResultPart <- function(iType, objIndex, varIndex, firstPeriod, lastPeriod) {
    .Call('_swmmr_GetSwmmResultPart', PACKAGE = 'swmmr', iType, objIndex, varIndex, firstPeriod, lastPeriod)
}

GetSwmmResultPart2 <- function(iType, objIndex, varIndices, firstPeriod, lastPeriod) {
    .Call('_swmmr_GetSwmmResultPart2', PACKAGE = 'swmmr', iType, objIndex, varIndices, firstPeriod, lastPeriod)
}

GetSwmmResult <- function(iType, iIndex, vIndex) {
    .Call('_swmmr_GetSwmmResult', PACKAGE = 'swmmr', iType, iIndex, vIndex)
}

GetSwmmTimes <- function() {
    .Call('_swmmr_GetSwmmTimes', PACKAGE = 'swmmr')
}

CloseSwmmOutFile <- function() {
    .Call('_swmmr_CloseSwmmOutFile', PACKAGE = 'swmmr')
}

